package com.y9vad9.rsocket.router.service.proto.codegen

internal object Constant {
    val GENERATED_COMMENT = """
        This file is generated by the `rsocket-kotlin-router` library.

        WARNING: DO NOT MODIFY THIS FILE MANUALLY!

        Any changes made to this file will be overwritten when the code is regenerated.
    """.trimIndent()
}